# Generated by Django 5.0.1 on 2024-02-06 12:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor do Empréstimo",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True,
                        default=None,
                        verbose_name="Data de Solicitação do Empréstimo",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, verbose_name="Parcela foi paga?"
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loans.loans",
                        verbose_name="Empréstimo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
        ),
    ]
