# Generated by Django 5.0.1 on 2024-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="installment_number",
            field=models.IntegerField(
                default=1,
                verbose_name="Identificador da Parcela do Empréstimo",
            ),
            preserve_default=False,
        ),
    ]
